server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # redirect /inventario (no slash) to /inventario/index
    location = /inventario {
        
        
        sub_filter '<base href="/">' '<base href="/inventario/">';
		sub_filter_once on;
		sub_filter_types text/html;

    }

    # Serve SPA for any /inventario/* path by returning the root index.html
    location ^~ /inventario/ {
        # If a static file exists at the requested path (e.g. assets), serve it,
        # otherwise return the root index.html so the SPA router handles the path.
        try_files $uri $uri/ /index.html;
    }

}

