# Generated by Django 5.0.3 on 2024-07-23 04:38

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=150, unique=True)),
                ('asiento', models.IntegerField()),
                ('no_identificacion', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('serie', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(blank=True, choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('REGULAR', 'REGULAR')], max_length=7)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_el', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('observacion', models.TextField(blank=True)),
                ('impreso', models.IntegerField(default=False)),
                ('conectividad', models.BooleanField(default=False)),
                ('seguridad', models.BooleanField(default=False)),
                ('placa_impresa', models.BooleanField(default=False)),
                ('de_baja', models.CharField(choices=[('NO DADO DE BAJA', 'NO DADO DE BAJA'), ('DADO DE BAJA CON PLACA', 'DADO DE BAJA CON PLACA'), ('DADO DE BAJA SIN PLACA', 'DADO DE BAJA SIN PLACA')], default='NO DADO DE BAJA', max_length=25)),
            ],
            options={
                'db_table': 'activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'EXCEL')], max_length=5)),
                ('ruta', models.CharField(max_length=250)),
                ('creado_el', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'docs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=150, unique=True)),
                ('asiento', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('impreso', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'observaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'db_table': 'puestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadActivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=150)),
                ('asiento', models.IntegerField()),
                ('no_identificacion', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('serie', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(blank=True, choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('REGULAR', 'REGULAR')], max_length=7)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_el', models.DateTimeField()),
                ('impreso', models.BooleanField(default=False)),
                ('conectividad', models.BooleanField(default=False)),
                ('seguridad', models.BooleanField(default=False)),
                ('placa_impresa', models.BooleanField(default=False)),
                ('de_baja', models.CharField(choices=[('NO DADO DE BAJA', 'NO DADO DE BAJA'), ('DADO DE BAJA CON PLACA', 'DADO DE BAJA CON PLACA'), ('DADO DE BAJA SIN PLACA', 'DADO DE BAJA SIN PLACA')], default='NO DADO DE BAJA', max_length=25)),
            ],
            options={
                'db_table': 'activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModoAdquisicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=240, unique=True)),
            ],
            options={
                'db_table': 'modoadquisicion',
            },
        ),
        migrations.CreateModel(
            name='Plantillas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('OBSERVACION', 'OBSERVACION'), ('ACTA B', 'ACTA B'), ('ACTA T', 'ACTA T'), ('REVISIONES NOTAS', 'REVISIONES NOTAS')], max_length=21)),
            ],
            options={
                'db_table': 'plantillas',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.departamentos')),
                ('puesto', models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.puestos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='CierreInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_revision', models.CharField(choices=[('PRINCIPIO', 'PRINCIPIO'), ('MEDIO', 'MEDIO'), ('FINAL', 'FINAL')], max_length=10)),
                ('fecha', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(db_column='funcionario', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.funcionarios')),
            ],
            options={
                'db_table': 'cierreinventario',
            },
        ),
        migrations.CreateModel(
            name='Revisiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SI EXISTE', 'SI EXISTE'), ('NO EXISTE', 'NO EXISTE')], max_length=11)),
                ('fecha', models.DateField(null=True)),
                ('nota', models.TextField(null=True)),
                ('cierre_inventario_id', models.ForeignKey(db_column='cierre_inventario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.cierreinventario')),
                ('id_registro', models.ForeignKey(db_column='id_registro', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.activos', to_field='id_registro')),
            ],
            options={
                'db_table': 'revisiones',
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_oficial', models.CharField(blank=True, max_length=240, unique=True)),
                ('alias', models.CharField(blank=True, max_length=240, null=True, unique=True)),
                ('img_path', models.CharField(blank=True, max_length=250)),
                ('funcionario_id', models.ForeignKey(blank=True, db_column='funcionario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('activo', models.ForeignKey(db_column='activo', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.activos', to_field='id_registro')),
                ('ubicacion', models.ForeignKey(db_column='ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ubicaciones')),
            ],
            options={
                'db_table': 'historialubicaciones',
            },
        ),
        migrations.AddField(
            model_name='cierreinventario',
            name='ubicacion',
            field=models.ForeignKey(db_column='aula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ubicaciones'),
        ),
    ]
