# Generated by Django 5.0.3 on 2024-07-16 05:04

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=150, unique=True)),
                ('asiento', models.IntegerField()),
                ('no_identificacion', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('serie', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(blank=True, choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('REGULAR', 'REGULAR')], max_length=7)),
                ('ubicacion', models.CharField(max_length=255)),
                ('modo_adquisicion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_el', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('observacion', models.TextField(blank=True)),
                ('impreso', models.IntegerField(default=False)),
            ],
            options={
                'db_table': 'activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'db_table': 'aulas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'EXCEL')], max_length=5)),
                ('ruta', models.CharField(max_length=250)),
                ('creado_el', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'docs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=150, unique=True)),
                ('asiento', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('impreso', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'observaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'db_table': 'puestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadActivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=150)),
                ('asiento', models.IntegerField()),
                ('no_identificacion', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('serie', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(blank=True, choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('REGULAR', 'REGULAR')], max_length=7)),
                ('ubicacion', models.CharField(max_length=255)),
                ('modo_adquisicion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_el', models.DateTimeField()),
                ('impreso', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('aula', models.ForeignKey(db_column='aula', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.aulas')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.departamentos')),
                ('puesto', models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.puestos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extra_info',
            },
        ),
    ]
