# Generated by Django 5.0.3 on 2024-07-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='alias',
            field=models.CharField(default=models.CharField(max_length=240, unique=True), max_length=240, unique=True),
        ),
    ]
