# Generated by Django 5.0.3 on 2024-07-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_ExtraInfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_revision', models.CharField(choices=[('PRINCIPIO', 'PRINCIPIO'), ('MEDIO', 'MEDIO'), ('FINAL', 'FINAL')], max_length=10)),
                ('finalizado', models.BooleanField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.aulas')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.extrainfo')),
            ],
            options={
                'db_table': 'cierrerevisiones',
            },
        ),
    ]
