# Generated by Django 5.0.3 on 2024-07-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extrainfo',
            table='extra_info',
        ),
    ]
