# Generated by Django 5.0.3 on 2024-07-30 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_ubicaciones_funcionario_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDeAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Observador', 'Observador'), ('Funcionario', 'Funcionario')], max_length=20)),
                ('fecha_hora_acceso', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historiales de Acceso',
                'db_table': 'historialacceso',
            },
        ),
    ]
