# Generated by Django 5.0.3 on 2024-07-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_cierreinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreinventario',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
