# Generated by Django 5.0.3 on 2024-07-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_ubicaciones_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='alias',
            field=models.CharField(max_length=240, null=True, unique=True),
        ),
    ]
