# Generated by Django 5.0.3 on 2024-07-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_cierreinventario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreinventario',
            name='aula',
            field=models.ForeignKey(db_column='aula', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.aulas'),
        ),
        migrations.AlterField(
            model_name='cierreinventario',
            name='profesor',
            field=models.ForeignKey(db_column='profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.extrainfo'),
        ),
    ]
