# Generated by Django 5.0.3 on 2024-07-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_cierreinventario_aula_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cierreinventario',
            table='cierreinventario',
        ),
    ]
