# Generated by Django 5.0.3 on 2024-07-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_funcionarios_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('activo', models.ForeignKey(db_column='activo', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.activos', to_field='id_registro')),
                ('ubicacion', models.ForeignKey(db_column='ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ubicaciones')),
            ],
            options={
                'db_table': 'historialubicaciones',
            },
        ),
    ]
