# Generated by Django 5.0.3 on 2024-07-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historialubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoAdquisicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'modoadquisicion',
            },
        ),
    ]
