# Generated by Django 5.0.3 on 2024-07-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_cierreinventario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SI EXISTE', 'SI EXISTE'), ('NO EXISTE', 'NO EXISTE')], max_length=11)),
                ('fecha', models.DateField(null=True)),
                ('nota', models.TextField(null=True)),
                ('cierre_inventario_id', models.ForeignKey(db_column='cierre_inventario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.cierreinventario')),
                ('id_registro', models.ForeignKey(db_column='id_registro', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.activos', to_field='id_registro')),
            ],
            options={
                'db_table': 'revisiones',
            },
        ),
    ]
