# Generated by Django 5.0.3 on 2024-07-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_modoadquisicion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modoadquisicion',
            name='descripcion',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
