# Generated by Django 5.0.3 on 2024-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_modoadquisicion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantillas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(blank=True, choices=[('OBSERVACION', 'OBSERVACION'), ('ACTA B', 'ACTA B'), ('ACTA T', 'ACTA T'), ('REVISIONES NOTAS', 'REVISIONES NOTAS')], max_length=21)),
            ],
            options={
                'db_table': 'plantillas',
            },
        ),
    ]
