# Generated by Django 5.0.3 on 2024-07-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_plantillas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='tipo',
            field=models.CharField(choices=[('OBSERVACION', 'OBSERVACION'), ('ACTA B', 'ACTA B'), ('ACTA T', 'ACTA T'), ('REVISIONES NOTAS', 'REVISIONES NOTAS')], max_length=21),
        ),
    ]
