# Generated by Django 5.0.3 on 2024-07-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_plantillas_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modoadquisicion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=240, unique=True),
        ),
    ]
