server {
    listen 8080;

	root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
	
	location @fallback {
		try_files /index.html;
	}

	#Si alguien esta leyendo esto, y lo entiende, puede intentar arreglar el error que 
    #el docker que contiene el frontend no logra conectar al docker del backend internamente
    #Esto que esta comentado deberia servir pero por alguna razon no
    #location /api/ {
     #   proxy_pass http://django:8000;
      #  proxy_set_header Host $host;
       # proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #}
}
